nginx:
  enabled: false

ingress:
  enabled: true
  defaultBackend:
    enabled: true
  hosts:
    - "HOSTNAME"
  routerPath: /
  artifactoryPath: /artifactory/
  annotations: 
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "2400"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "2400"
    ####Optional annotations:
    #nginx.ingress.kubernetes.io/proxy-buffering: "off"
    #nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    #nginx.ingress.kubernetes.io/proxy-max-temp-file-size: "0"
