artifactory:
  copyOnEveryStartup:
      - source: /artifactory_bootstrap/binarystore.xml
        target: etc/artifactory/  
  customVolumes: |
    - name: "nfs-vol"
      persistentVolumeClaim:
        claimName: "artifactory-ha-nfs-pvc-nfs"
  customVolumeMounts: |
    - name: "nfs-vol" 
      mountPath: "/nfs"
  persistence:
    type: "file-system"
    binarystoreXml:
      <config version="v1">
      <chain>
          <provider id="cache-fs" type="cache-fs">
              <provider id="file-system" type="file-system"/>
          </provider>
      </chain>
      
      <provider id="cache-fs" type="cache-fs">
          <cacheProviderDir>/opt/jfrog/artifactory/var/data/artifactory/cache</cacheProviderDir>
          <maxCacheSize>50000000000</maxCacheSize>
      </provider>
      
      <provider id="file-system" type="file-system">
          <fileStoreDir>/nfs/filestore</fileStoreDir>
      </provider>
      </config>
