artifactory-ha:
  enabled: true
  postgresql:
    enabled: false
  waitForDatabase: false
  database:
    type: postgresql
    driver: org.postgresql.Driver
    url: jdbc:postgresql://POSTGRESQL_HOST:5432/artifactory?sslmode=
    user: artifactory
    password: password
xray:
  enabled: true
  unifiedUpgradeAllowed: true
  postgresql:
    enabled: false
  database:
    url: postgres://POSTGRESQL_HOST:5432/xray?sslmode=
    user: xray
    password: password

distribution:
  enabled: true
  unifiedUpgradeAllowed: true
  postgresql:
    enabled: false
  database:
    url: jdbc:postgresql://POSTGRESQL_HOST:5432/distribution?sslmode=
    user: distribution
    password: password

mission-control:
  enabled: true
  unifiedUpgradeAllowed: true
  postgresql:
    enabled: false
  database:
    url: jdbc:postgresql://POSTGRESQL_HOST:5432/mission_control?sslmode=
    user: mc
    password: password
    name: mission_control
