artifactory-ha:
  enabled: true
  postgresql:
    enabled: false
  waitForDatabase: false
  database:
    type: postgresql
    driver: org.postgresql.Driver
    url: jdbc:postgresql://POSTGRESQL_HOST:5432/artifactorydb?sslmode=
    user: artifactoryha
    password: artifactoryha
xray:
  enabled: true
  unifiedUpgradeAllowed: true
  postgresql:
    enabled: false
  database:
    url: postgres://POSTGRESQL_HOST:5432/xray?sslmode=
    user: xray
    password: xray

distribution:
  enabled: true
  unifiedUpgradeAllowed: true
  postgresql:
    enabled: false
  database:
    url: jdbc:postgresql://POSTGRESQL_HOST:5432/artifactorydb?sslmode=
    user: distribution
    password: distribution

mission-control:
  enabled: true
  unifiedUpgradeAllowed: true
  postgresql:
    enabled: false
  database:
    url: jdbc:postgresql://POSTGRESQL_HOST:5432/mission_control?sslmode=
    user: jfmc
    password: jfmc
    name: mission_control
