artifactory:
  serviceAccount:
    create: true
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/<IAM_ROLE_NAME>
  artifactory:
    copyOnEveryStartup:
      - source: /artifactory_bootstrap/binarystore.xml
        target: etc/artifactory/
    persistence:
      type: "aws-s3-v3"
      maxCacheSize: 50000000000
      awsS3V3:
        testConnection: false
        region: 
        bucketName: 
        path: artifactory/filestore
