apiVersion: v1
kind: PersistentVolume
metadata:
  name: artifactory-ha-data-pv-nfs1
  labels:
    id: artifactory-ha-data-pv-nfs1
    type: nfs-volume
spec:
  capacity:
    storage: 200Gi 
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "10.0.0.1"
    path: "/data1" 
    readOnly: false
