kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: artifactory-ha-nfs-pvc-nfs2
  labels:
    type: nfs-volume
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 200Gi 
  selector:
    matchLabels:
      id: artifactory-ha-data-pv-nfs2
